### ISSUE TITLE
"disk only" mode cache hits are not counted in statistics

### ISSUE THREAD

**Issue by zoltanbalog79** [jiangwenyuan/nuster#51]
BUG: In the statistics the 'req_hit' does not count the cache hits in "disk only" mode. The value is always 0.

A typical output of the statistics page after many thousands of successful cached requests:

curl localhost/_nuster_stats
**GLOBAL**
global.nuster.cache.data.size: 1073741824
global.nuster.cache.dict.size: 1073741824
global.nuster.cache.uri: /_nuster_stats
global.nuster.cache.purge_method: PURGE
global.nuster.cache.stats.used_mem: 0
global.nuster.cache.stats.req_total: 151190
global.nuster.cache.stats.req_hit: 0
global.nuster.cache.stats.req_fetch: 25190
global.nuster.cache.stats.req_abort: 0

**Comment by jiangwenyuan** [comment]
@zoltanbalog79 Thanks.

Currently, disk support in stats and purge is not yet finished. (almost finished purge, testing...)

**Comment by jiangwenyuan** [comment]
@zoltanbalog79 fixed in master, thanks

**Comment by netrixken** [comment]
this bug still exists in 3.2.0.19. /tmp/cache is empty so cache hits always 0

```
**GLOBAL**
global.nuster.cache.data.size: 33554432
global.nuster.cache.dict.size: 1048576
global.nuster.cache.uri: /nuster/cache
global.nuster.cache.purge_method: PURGE
global.nuster.cache.stats.used_mem: 0
global.nuster.cache.stats.req_total: 3496
global.nuster.cache.stats.req_hit: 0
global.nuster.cache.stats.req_fetch: 3371
global.nuster.cache.stats.req_abort: 10

**PERSISTENCE**
global.nuster.cache.dir: /tmp/cache
global.nuster.cache.loaded: yes
```

GLOBAL

```
master-worker
nuster cache on data-size 32m dir /tmp/cache uri /nuster/cache
nuster nosql off
```

BACKEND

```
nuster cache on
nuster rule server_blog disk only ttl 2h
http-response set-header x-cache hit if { nuster.cache.hit }
```

**Comment by jiangwenyuan** [comment]
Confirmed break on `disk only` mode, but works on `disk sync` mode

**Comment by jiangwenyuan** [comment]
@netrixken fixed in v3.2.1.19

**Comment by netrixken** [comment]
Thank you for your fast fixed! But, may I know where the cache is stored (disk only)? Because my /tmp/cache is empty (not empty when disk async/sync is used) and req_hit still always 0..

**Comment by netrixken** [comment]
it worked now. i delete these leftover configuration. thank you very much!

```
    chroot      /var/lib/haproxy
    maxconn     2048
    user        haproxy
    group       haproxy
    daemon
```

**Comment by netrixken** [comment]
It worked now. I delete these leftover haproxy configuration from nuster config. Thank you very much!

```
    chroot      /var/lib/haproxy
    user        haproxy
    group       haproxy
```

Now, only `used_mem` is still always 0. Or disk cache not counted as `used_mem`?

**Comment by jiangwenyuan** [comment]
@netrixken  

> only used_mem is still always 0. Or disk cache not counted as used_mem?

`disk only` mode does not use memory, except temporary memory.

>     chroot      /var/lib/haproxy

If you have this setting, the cache file is stored into `/var/lib/haproxy/tmp/cache` (chroot-dir + cache-dir)

**Comment by netrixken** [comment]
If for example i have 100 MB RAM, how much the biggest data-size I can set? Thanks @jiangwenyuan

**Comment by jiangwenyuan** [comment]
@netrixken Well, it's hard to say.  Higher values allow more cache and lower values allow more sessions to coexist in the same time. I'd suggest you start with half of the RAM and test.

**Comment by jiangwenyuan** [comment]
@netrixken I'm closing it now, feel free to reopen the issue if anything wrong
