### ISSUE TITLE
Nuster used too much memory and freezed

### ISSUE THREAD

**Issue by netrixken** [jiangwenyuan/nuster#65]
```
Broadcast message from systemd-journald@kvm-NetVPS36 (Sun 2020-04-12 13:27:38 WIB):

nuster[4098]: A bogus STREAM [0x7f6cd52a7220] is spinning at 100000 calls per second and refuses to die, aborting now! Please report this error to developers [strm=0x7f6cd52a7220 src=::ffff:116.206.39.110 fe=main_frontend be=server_blog dst=<NUSTER.CACHE.ENGINE> rqf=6d800000 rqa=48000 rpf=a8040002 rpa=24000000 sif=EST,250000 sib=EST,44118 af=(nil),0 csf=0x7f6cc40539c0,10c000 ab=0x7f6cc40c4700,4 csb=(nil),0 cof=0x7f6cc4028090,80203360:H1(0x7f6cc4081760)/SSL(0x7f6cc4092040)/tcpv6(39) cob=(nil),0:NONE((nil))/NONE((nil))/NONE(0) ]


Message from syslogd@kvm-NetVPS36 at Apr 12 13:27:38 ...
 nuster[4098]: A bogus STREAM [0x7f6cd52a7220] is spinning at 100000 calls per second and refuses to die, aborting now! Please report this error to developers [strm=0x7f6cd52a7220 src=::ffff:116.206.39.110 fe=main_frontend be=server_blog dst=<NUSTER.CACHE.ENGINE> rqf=6d800000 rqa=48000 rpf=a8040002 rpa=24000000 sif=EST,250000 sib=EST,44118 af=(nil),0 csf=0x7f6cc40539c0,10c000 ab=0x7f6cc40c4700,4 csb=(nil),0 cof=0x7f6cc4028090,80203360:H1(0x7f6cc4081760)/SSL(0x7f6cc4092040)/tcpv6(39) cob=(nil),0:NONE((nil))/NONE((nil))/NONE(0) ]

Message from syslogd@kvm-NetVPS36 at Apr 12 13:27:38 ...
 nuster[4098]: A bogus STREAM [0x7f6cd52a7220] is spinning at 100000 calls per second and refuses to die, aborting now! Please report this error to developers [strm=0x7f6cd52a7220 src=::ffff:116.206.39.110 fe=main_frontend be=server_blog dst=<NUSTER.CACHE.ENGINE> rqf=6d800000 rqa=48000 rpf=a8040002 rpa=24000000 sif=EST,250000 sib=EST,44118 af=(nil),0 csf=0x7f6cc40539c0,10c000 ab=0x7f6cc40c4700,4 csb=(nil),0 cof=0x7f6cc4028090,80203360:H1(0x7f6cc4081760)/SSL(0x7f6cc4092040)/tcpv6(39) cob=(nil),0:NONE((nil))/NONE((nil))/NONE(0) ]

Broadcast message from systemd-journald@kvm-NetVPS36 (Sun 2020-04-12 13:27:38 WIB):

nuster[4098]: A bogus STREAM [0x7f6cd52a7220] is spinning at 100000 calls per second and refuses to die, aborting now! Please report this error to developers [strm=0x7f6cd52a7220 src=::ffff:116.206.39.110 fe=main_frontend be=server_blog dst=<NUSTER.CACHE.ENGINE> rqf=6d800000 rqa=48000 rpf=a8040002 rpa=24000000 sif=EST,250000 sib=EST,44118 af=(nil),0 csf=0x7f6cc40539c0,10c000 ab=0x7f6cc40c4700,4 csb=(nil),0 cof=0x7f6cc4028090,80203360:H1(0x7f6cc4081760)/SSL(0x7f6cc4092040)/tcpv6(39) cob=(nil),0:NONE((nil))/NONE((nil))/NONE(0) ]
```

Version: 5.0.0.21

*** GLOBAL ***
```
nuster cache on data-size 100m dir /opt/nuster/cache
nuster manager on uri /stat/nuster purge-method PURGEX
```

*** BACKEND ***
```
nuster cache on
acl static_content path_end -i .jpg .png .gif .css .js .ico
nuster rule server_v1 disk on memory off ttl 2h extend on if static_content
http-response set-header n-cache hit if { nuster.cache.hit }
```

**Comment by jiangwenyuan** [comment]
@netrixken Thanks for reporting, fixed in https://github.com/jiangwenyuan/nuster/tree/H2.1

Can you try branch H2.1?

**Comment by netrixken** [comment]
The problem still persist, after error like shown below, Nuster is crashed.

```
Broadcast message from systemd-journald@kvm-NetVPS36 (Mon 2020-04-13 21:26:53 WIB):

nuster[14121]: A bogus STREAM [0x7efd601b10c0] is spinning at 116832 calls per second and refuses to die, aborting now! Please report this error to developers [strm=0x7efd601b10c0 src=::ffff:36.73.33.49 fe=main_frontend be=server_blog_v2 dst=<NUSTER.CACHE.ENGINE> rqf=6dc00000 rqa=48000 rpf=a8000002 rpa=24000000 sif=EST,58000 sib=EST,44118 af=(nil),0 csf=0x7efd717ad270,104000 ab=0x7efd7179f5c0,4 csb=(nil),0 cof=0x7efd602ad090,80203366:H2(0x7efd7195e980)/SSL(0x7efd71813a30)/tcpv6(32) cob=(nil),0:NONE((nil))/NONE((nil))/NONE(0) ]


Broadcast message from systemd-journald@kvm-NetVPS36 (Mon 2020-04-13 21:26:53 WIB):

nuster[14121]: A bogus STREAM [0x7efd601b10c0] is spinning at 116832 calls per second and refuses to die, aborting now! Please report this error to developers [strm=0x7efd601b10c0 src=::ffff:36.73.33.49 fe=main_frontend be=server_blog_v2 dst=<NUSTER.CACHE.ENGINE> rqf=6dc00000 rqa=48000 rpf=a8000002 rpa=24000000 sif=EST,58000 sib=EST,44118 af=(nil),0 csf=0x7efd717ad270,104000 ab=0x7efd7179f5c0,4 csb=(nil),0 cof=0x7efd602ad090,80203366:H2(0x7efd7195e980)/SSL(0x7efd71813a30)/tcpv6(32) cob=(nil),0:NONE((nil))/NONE((nil))/NONE(0) ]


Message from syslogd@kvm-NetVPS36 at Apr 13 21:26:53 ...
 nuster[14121]: A bogus STREAM [0x7efd601b10c0] is spinning at 116832 calls per second and refuses to die, aborting now! Please report this error to developers [strm=0x7efd601b10c0 src=::ffff:36.73.33.49 fe=main_frontend be=server_blog_v2 dst=<NUSTER.CACHE.ENGINE> rqf=6dc00000 rqa=48000 rpf=a8000002 rpa=24000000 sif=EST,58000 sib=EST,44118 af=(nil),0 csf=0x7efd717ad270,104000 ab=0x7efd7179f5c0,4 csb=(nil),0 cof=0x7efd602ad090,80203366:H2(0x7efd7195e980)/SSL(0x7efd71813a30)/tcpv6(32) cob=(nil),0:NONE((nil))/NONE((nil))/NONE(0) ]

Message from syslogd@kvm-NetVPS36 at Apr 13 21:26:53 ...
 nuster[14121]: A bogus STREAM [0x7efd601b10c0] is spinning at 116832 calls per second and refuses to die, aborting now! Please report this error to developers [strm=0x7efd601b10c0 src=::ffff:36.73.33.49 fe=main_frontend be=server_blog_v2 dst=<NUSTER.CACHE.ENGINE> rqf=6dc00000 rqa=48000 rpf=a8000002 rpa=24000000 sif=EST,58000 sib=EST,44118 af=(nil),0 csf=0x7efd717ad270,104000 ab=0x7efd7179f5c0,4 csb=(nil),0 cof=0x7efd602ad090,80203366:H2(0x7efd7195e980)/SSL(0x7efd71813a30)/tcpv6(32) cob=(nil),0:NONE((nil))/NONE((nil))/NONE(0) ]
```

**Comment by jiangwenyuan** [comment]
Hmm, can you share a complete config file?

**Comment by netrixken** [comment]
```
global
	log /dev/log	local0 notice
	log /dev/log	local1 notice
	pidfile			/var/run/nuster.pid
	
	# Nuster configuration
	master-worker
	nuster cache on data-size 100m dir /opt/nuster/cache
	nuster manager on uri /stat/nuster purge-method PURGEX

    # turn on stats unix socket
    stats socket /run/nuster.sock mode 660 level admin expose-fd listeners
    stats timeout 30s
    
    # Default SSL material locations
	ca-base /etc/ssl/certs
	crt-base /etc/ssl/private

	# Default ciphers to use on SSL-enabled listening sockets.
	# For more information, see ciphers(1SSL). This list is from:
	#  https://hynek.me/articles/hardening-your-web-servers-ssl-ciphers/
	ssl-default-bind-ciphers ECDH+AESGCM:DH+AESGCM:ECDH+AES256:DH+AES256:ECDH+AES128:DH+AES:RSA+AESGCM:RSA+AES:!aNULL:!MD5:!DSS
	ssl-default-bind-options no-sslv3
	tune.ssl.default-dh-param	2048

#---------------------------------------------------------------------
# common defaults that all the 'listen' and 'backend' sections will
# use if not designated in their block
#---------------------------------------------------------------------
defaults
	log								global
	mode							http
	option							httplog
	option							dontlognull
	option							redispatch
	retries							3
	timeout		http-request		30s
	timeout		queue				1m
	timeout		connect				30s
	timeout		client				1m
	timeout		server				1m
	timeout		http-keep-alive		10s
	timeout		check				5s
	maxconn							2048
	
	errorfile 400 /etc/nuster/errors/400.http
	errorfile 403 /etc/nuster/errors/403.http
	errorfile 408 /etc/nuster/errors/408.http
	errorfile 500 /etc/nuster/errors/500.http
	errorfile 502 /etc/nuster/errors/502.http
	errorfile 503 /etc/nuster/errors/503.http
	errorfile 504 /etc/nuster/errors/504.http
	
listen admin_page
	bind 	:::5151
	mode	http
    stats	enable
    stats	hide-version
    stats	realm Strictly\ Private
    stats	uri /
    stats	auth admin:netrix@638749

#---------------------------------------------------------------------
# main frontend which proxys to the backends
#---------------------------------------------------------------------
frontend main_frontend
	bind :::80
	bind :::443 ssl crt-list MY_CRTs_LIST alpn h2,http/1.1
	
	# Options
	mode http
	option http-server-close
	option forwardfor except 127.0.0.0/8
	
	# ACL
	# HTTPS
	acl domain_https hdr(Host) -i MY_SITES
	redirect scheme https code 301 if domain_https !{ ssl_fc }
	
	# Path administrator
	acl main_server path_beg /wp-admin
	
	# Test URI to see if its a letsencrypt request
	acl letsencrypt path_beg /.well-known/acme-challenge/
	
	# Domain AGC
	acl	domain_agc			hdr(Host)	-i	MY_SITES
	
	# Domain blog
	acl	domain_blog_v1		hdr(Host)	-i	MY_SITES
	acl	domain_blog_v2		hdr(Host)	-i	MY_SITES
		
	# Domain iklan
	acl	domain_iklan_v1		hdr(Host)	-i	MY_SITES
	acl	domain_iklan_v2		hdr(Host)	-i	MY_SITES
	acl	domain_iklan_v3		hdr(Host)	-i	MY_SITES
		
	# Backend
	use_backend	backup_server		if	letsencrypt
	
	use_backend	localhttp			if	domain_agc
	
	use_backend	server_blog_u		if	domain_blog_v1	main_server
	use_backend	server_blog			if	domain_blog_v1

	use_backend	server_blog_v2_u	if	domain_blog_v2	main_server
	use_backend	server_blog_v2		if	domain_blog_v2
		
	use_backend	server_iklan_v1_u	if	domain_iklan_v1	main_server
	use_backend	server_iklan_v1		if	domain_iklan_v1
	
	use_backend	server_iklan_v2_u	if	domain_iklan_v2	main_server
	use_backend	server_iklan_v2		if	domain_iklan_v2
	
	use_backend	server_iklan_v3_u	if	domain_iklan_v3	main_server
	use_backend	server_iklan_v3		if	domain_iklan_v3
	
	# General backend
	default_backend backup_server
	
backend localhttp
	mode http
	
	option	http-server-close
	option	forwardfor	except 127.0.0.0/8
	
	server	local		127.0.0.1:5678
	
backend server_blog
	mode http

	# Nuster configuration
	nuster cache on
	acl static_content path_end -i .jpg .png .gif .css .js .ico
	nuster rule server_blog disk on memory off ttl 2h extend on if static_content
	http-response set-header n-cache hit if { nuster.cache.hit }
	
	option	http-server-close
	option	forwardfor	except 127.0.0.0/8
	option	httpchk		HEAD /check.php5 "HTTP/1.1\r\nHost: localhost\r\nConnection: close"
	
	http-request set-header X-Forwarded-Port %[dst_port]
	http-request add-header X-Forwarded-Proto https if { ssl_fc }
	
	server	NetVPS54	MY_IP	check	inter	5s	fall	3	rise	3
	server	NetVPS43	MY_IP	backup
	
backend server_blog_u
	mode http
	
	option http-server-close
	option forwardfor except 127.0.0.0/8
	
	http-request set-header X-Forwarded-Port %[dst_port]
	http-request add-header X-Forwarded-Proto https if { ssl_fc }
	
	server NetVPS54		MY_IP

backend server_blog_v2
	mode http

	# Nuster configuration
	nuster cache on
	acl static_content path_end -i .jpg .png .gif .css .js .ico
	nuster rule server_blog_v2 disk on memory off ttl 2h extend on if static_content
	http-response set-header n-cache hit if { nuster.cache.hit }
	
	option http-server-close
	option	forwardfor	except 127.0.0.0/8
	option	httpchk		HEAD /check.php5 "HTTP/1.1\r\nHost: localhost\r\nConnection: close"
	
	http-request set-header X-Forwarded-Port %[dst_port]
	http-request add-header X-Forwarded-Proto https if { ssl_fc }

	server	NetVPS53	MY_IP		check	inter	5s	fall	3	rise	3
	server	NetVPS43	MY_IP		backup
	
backend server_blog_v2_u
	mode http
	
	option http-server-close
	option forwardfor except 127.0.0.0/8
	
	http-request set-header X-Forwarded-Port %[dst_port]
	http-request add-header X-Forwarded-Proto https if { ssl_fc }
	
	server	NetVPS53	MY_IP
	
backend server_iklan_v1
	mode http

	# Nuster configuration
	nuster cache on
	acl static_content path_end -i .jpg .png .gif .css .js .ico
	nuster rule server_iklan_v1 disk on memory off ttl 2h extend on if static_content
	http-response set-header n-cache hit if { nuster.cache.hit }
	
	option http-server-close
	option	forwardfor	except 127.0.0.0/8
	option	httpchk		HEAD /check.php5 "HTTP/1.1\r\nHost: localhost\r\nConnection: close"
	
	http-request set-header X-Forwarded-Port %[dst_port]
	http-request add-header X-Forwarded-Proto https if { ssl_fc }
	
	server	NetVPS57	MY_IP		check	inter	5s	fall	3	rise	3
	server	NetVPS43	MY_IP		backup
	
backend server_iklan_v1_u
	mode http
	
	option http-server-close
	option forwardfor except 127.0.0.0/8
	
	http-request set-header X-Forwarded-Port %[dst_port]
	http-request add-header X-Forwarded-Proto https if { ssl_fc }
	
	server NetVPS57		MY_IP
	
backend server_iklan_v2
	mode http

	# Nuster configuration
	nuster cache on
	acl static_content path_end -i .jpg .png .gif .css .js .ico
	nuster rule server_iklan_v2 disk on memory off ttl 2h extend on if static_content
	http-response set-header n-cache hit if { nuster.cache.hit }
	
	option http-server-close
	option	forwardfor	except 127.0.0.0/8
	option	httpchk		HEAD /check.php5 "HTTP/1.1\r\nHost: localhost\r\nConnection: close"
	
	http-request set-header X-Forwarded-Port %[dst_port]
	http-request add-header X-Forwarded-Proto https if { ssl_fc }
	
	server	NetVPS56	MY_IP		check	inter	5s	fall	3	rise	3
	server	NetVPS43	MY_IP		backup
	
backend server_iklan_v2_u
	mode http
	
	option http-server-close
	option forwardfor except 127.0.0.0/8
	
	http-request set-header X-Forwarded-Port %[dst_port]
	http-request add-header X-Forwarded-Proto https if { ssl_fc }
	
	server NetVPS56		MY_IP
	
backend server_iklan_v3
	mode http

	# Nuster configuration
	nuster cache on
	acl static_content path_end -i .jpg .png .gif .css .js .ico
	nuster rule server_iklan_v3 disk on memory off ttl 2h extend on if static_content
	http-response set-header n-cache hit if { nuster.cache.hit }
	
	option http-server-close
	option	forwardfor	except 127.0.0.0/8
	option	httpchk		HEAD /check.php5 "HTTP/1.1\r\nHost: localhost\r\nConnection: close"
	
	http-request set-header X-Forwarded-Port %[dst_port]
	http-request add-header X-Forwarded-Proto https if { ssl_fc }
	
	server	NetVPS44	MY_IP		check	inter	5s	fall	3	rise	3
	server	NetVPS43	MY_IP		backup
	
backend server_iklan_v3_u
	mode http
	
	option http-server-close
	option forwardfor except 127.0.0.0/8
	
	http-request set-header X-Forwarded-Port %[dst_port]
	http-request add-header X-Forwarded-Proto https if { ssl_fc }
	
	server NetVPS44 MY_IP
		
backend backup_server
	mode http
	
	option http-server-close
	option forwardfor except 127.0.0.0/8
	
	http-request set-header X-Forwarded-Port %[dst_port]
	http-request add-header X-Forwarded-Proto https if { ssl_fc }
	
	server NetVPS43 MY_IP
	

```

**Comment by netrixken** [comment]
```
global
	log /dev/log	local0 notice
	log /dev/log	local1 notice
	pidfile			/var/run/nuster.pid
	
	# Nuster configuration
	master-worker
	nuster cache on data-size 100m dir /opt/nuster/cache
	nuster manager on uri /stat/nuster purge-method PURGEX

    # turn on stats unix socket
    stats socket /run/nuster.sock mode 660 level admin expose-fd listeners
    stats timeout 30s
    
    # Default SSL material locations
	ca-base /etc/ssl/certs
	crt-base /etc/ssl/private

	# Default ciphers to use on SSL-enabled listening sockets.
	# For more information, see ciphers(1SSL). This list is from:
	#  https://hynek.me/articles/hardening-your-web-servers-ssl-ciphers/
	ssl-default-bind-ciphers ECDH+AESGCM:DH+AESGCM:ECDH+AES256:DH+AES256:ECDH+AES128:DH+AES:RSA+AESGCM:RSA+AES:!aNULL:!MD5:!DSS
	ssl-default-bind-options no-sslv3
	tune.ssl.default-dh-param	2048

#---------------------------------------------------------------------
# common defaults that all the 'listen' and 'backend' sections will
# use if not designated in their block
#---------------------------------------------------------------------
defaults
	log								global
	mode							http
	option							httplog
	option							dontlognull
	option							redispatch
	retries							3
	timeout		http-request		30s
	timeout		queue				1m
	timeout		connect				30s
	timeout		client				1m
	timeout		server				1m
	timeout		http-keep-alive		10s
	timeout		check				5s
	maxconn							2048
	
	errorfile 400 /etc/nuster/errors/400.http
	errorfile 403 /etc/nuster/errors/403.http
	errorfile 408 /etc/nuster/errors/408.http
	errorfile 500 /etc/nuster/errors/500.http
	errorfile 502 /etc/nuster/errors/502.http
	errorfile 503 /etc/nuster/errors/503.http
	errorfile 504 /etc/nuster/errors/504.http
	
listen admin_page
	bind 	:::5151
	mode	http
    stats	enable
    stats	hide-version
    stats	realm Strictly\ Private
    stats	uri /
    stats	auth admin:abcde

#---------------------------------------------------------------------
# main frontend which proxys to the backends
#---------------------------------------------------------------------
frontend main_frontend
	bind :::80
	bind :::443 ssl crt-list MY_CRTs_LIST alpn h2,http/1.1
	
	# Options
	mode http
	option http-server-close
	option forwardfor except 127.0.0.0/8
	
	# ACL
	# HTTPS
	acl domain_https hdr(Host) -i MY_SITES
	redirect scheme https code 301 if domain_https !{ ssl_fc }
	
	# Path administrator
	acl main_server path_beg /wp-admin
	
	# Test URI to see if its a letsencrypt request
	acl letsencrypt path_beg /.well-known/acme-challenge/
	
	# Domain AGC
	acl	domain_agc			hdr(Host)	-i	MY_SITES
	
	# Domain blog
	acl	domain_blog_v1		hdr(Host)	-i	MY_SITES
	acl	domain_blog_v2		hdr(Host)	-i	MY_SITES
		
	# Domain iklan
	acl	domain_iklan_v1		hdr(Host)	-i	MY_SITES
	acl	domain_iklan_v2		hdr(Host)	-i	MY_SITES
	acl	domain_iklan_v3		hdr(Host)	-i	MY_SITES
		
	# Backend
	use_backend	backup_server		if	letsencrypt
	
	use_backend	localhttp			if	domain_agc
	
	use_backend	server_blog_u		if	domain_blog_v1	main_server
	use_backend	server_blog			if	domain_blog_v1

	use_backend	server_blog_v2_u	if	domain_blog_v2	main_server
	use_backend	server_blog_v2		if	domain_blog_v2
		
	use_backend	server_iklan_v1_u	if	domain_iklan_v1	main_server
	use_backend	server_iklan_v1		if	domain_iklan_v1
	
	use_backend	server_iklan_v2_u	if	domain_iklan_v2	main_server
	use_backend	server_iklan_v2		if	domain_iklan_v2
	
	use_backend	server_iklan_v3_u	if	domain_iklan_v3	main_server
	use_backend	server_iklan_v3		if	domain_iklan_v3
	
	# General backend
	default_backend backup_server
	
backend localhttp
	mode http
	
	option	http-server-close
	option	forwardfor	except 127.0.0.0/8
	
	server	local		127.0.0.1:5678
	
backend server_blog
	mode http

	# Nuster configuration
	nuster cache on
	acl static_content path_end -i .jpg .png .gif .css .js .ico
	nuster rule server_blog disk on memory off ttl 2h extend on if static_content
	http-response set-header n-cache hit if { nuster.cache.hit }
	
	option	http-server-close
	option	forwardfor	except 127.0.0.0/8
	option	httpchk		HEAD /check.php5 "HTTP/1.1\r\nHost: localhost\r\nConnection: close"
	
	http-request set-header X-Forwarded-Port %[dst_port]
	http-request add-header X-Forwarded-Proto https if { ssl_fc }
	
	server	NetVPS54	MY_IP	check	inter	5s	fall	3	rise	3
	server	NetVPS43	MY_IP	backup
	
backend server_blog_u
	mode http
	
	option http-server-close
	option forwardfor except 127.0.0.0/8
	
	http-request set-header X-Forwarded-Port %[dst_port]
	http-request add-header X-Forwarded-Proto https if { ssl_fc }
	
	server NetVPS54		MY_IP

backend server_blog_v2
	mode http

	# Nuster configuration
	nuster cache on
	acl static_content path_end -i .jpg .png .gif .css .js .ico
	nuster rule server_blog_v2 disk on memory off ttl 2h extend on if static_content
	http-response set-header n-cache hit if { nuster.cache.hit }
	
	option http-server-close
	option	forwardfor	except 127.0.0.0/8
	option	httpchk		HEAD /check.php5 "HTTP/1.1\r\nHost: localhost\r\nConnection: close"
	
	http-request set-header X-Forwarded-Port %[dst_port]
	http-request add-header X-Forwarded-Proto https if { ssl_fc }

	server	NetVPS53	MY_IP		check	inter	5s	fall	3	rise	3
	server	NetVPS43	MY_IP		backup
	
backend server_blog_v2_u
	mode http
	
	option http-server-close
	option forwardfor except 127.0.0.0/8
	
	http-request set-header X-Forwarded-Port %[dst_port]
	http-request add-header X-Forwarded-Proto https if { ssl_fc }
	
	server	NetVPS53	MY_IP
	
backend server_iklan_v1
	mode http

	# Nuster configuration
	nuster cache on
	acl static_content path_end -i .jpg .png .gif .css .js .ico
	nuster rule server_iklan_v1 disk on memory off ttl 2h extend on if static_content
	http-response set-header n-cache hit if { nuster.cache.hit }
	
	option http-server-close
	option	forwardfor	except 127.0.0.0/8
	option	httpchk		HEAD /check.php5 "HTTP/1.1\r\nHost: localhost\r\nConnection: close"
	
	http-request set-header X-Forwarded-Port %[dst_port]
	http-request add-header X-Forwarded-Proto https if { ssl_fc }
	
	server	NetVPS57	MY_IP		check	inter	5s	fall	3	rise	3
	server	NetVPS43	MY_IP		backup
	
backend server_iklan_v1_u
	mode http
	
	option http-server-close
	option forwardfor except 127.0.0.0/8
	
	http-request set-header X-Forwarded-Port %[dst_port]
	http-request add-header X-Forwarded-Proto https if { ssl_fc }
	
	server NetVPS57		MY_IP
	
backend server_iklan_v2
	mode http

	# Nuster configuration
	nuster cache on
	acl static_content path_end -i .jpg .png .gif .css .js .ico
	nuster rule server_iklan_v2 disk on memory off ttl 2h extend on if static_content
	http-response set-header n-cache hit if { nuster.cache.hit }
	
	option http-server-close
	option	forwardfor	except 127.0.0.0/8
	option	httpchk		HEAD /check.php5 "HTTP/1.1\r\nHost: localhost\r\nConnection: close"
	
	http-request set-header X-Forwarded-Port %[dst_port]
	http-request add-header X-Forwarded-Proto https if { ssl_fc }
	
	server	NetVPS56	MY_IP		check	inter	5s	fall	3	rise	3
	server	NetVPS43	MY_IP		backup
	
backend server_iklan_v2_u
	mode http
	
	option http-server-close
	option forwardfor except 127.0.0.0/8
	
	http-request set-header X-Forwarded-Port %[dst_port]
	http-request add-header X-Forwarded-Proto https if { ssl_fc }
	
	server NetVPS56		MY_IP
	
backend server_iklan_v3
	mode http

	# Nuster configuration
	nuster cache on
	acl static_content path_end -i .jpg .png .gif .css .js .ico
	nuster rule server_iklan_v3 disk on memory off ttl 2h extend on if static_content
	http-response set-header n-cache hit if { nuster.cache.hit }
	
	option http-server-close
	option	forwardfor	except 127.0.0.0/8
	option	httpchk		HEAD /check.php5 "HTTP/1.1\r\nHost: localhost\r\nConnection: close"
	
	http-request set-header X-Forwarded-Port %[dst_port]
	http-request add-header X-Forwarded-Proto https if { ssl_fc }
	
	server	NetVPS44	MY_IP		check	inter	5s	fall	3	rise	3
	server	NetVPS43	MY_IP		backup
	
backend server_iklan_v3_u
	mode http
	
	option http-server-close
	option forwardfor except 127.0.0.0/8
	
	http-request set-header X-Forwarded-Port %[dst_port]
	http-request add-header X-Forwarded-Proto https if { ssl_fc }
	
	server NetVPS44 MY_IP
		
backend backup_server
	mode http
	
	option http-server-close
	option forwardfor except 127.0.0.0/8
	
	http-request set-header X-Forwarded-Port %[dst_port]
	http-request add-header X-Forwarded-Proto https if { ssl_fc }
	
	server NetVPS43 MY_IP
	

```

**Comment by jiangwenyuan** [comment]
Thanks, and what's your OS?  The error appears without any traffics? It appears only under heavy traffics on my side.

This is a change brought in HAProxy v2, I fixed a bug which might trigger this error. Not sure if it's related to haproxy or not.

**Comment by netrixken** [comment]
Total traffic only ~50.000 view/day

```
root@kvm-NetVPS36:~# cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 9 (stretch)"
NAME="Debian GNU/Linux"
VERSION_ID="9"
VERSION="9 (stretch)"
VERSION_CODENAME=stretch
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
root@kvm-NetVPS36:~# uname -a
Linux kvm-NetVPS36 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt9-3~deb8u1 (2015-04-24) x86_64 GNU/Linux
```

**Comment by jiangwenyuan** [comment]
Use the same environment, same build, same config(except kernel 4.9.0 not 3.16) to stress test with wrk for almost 10 hours with random requests, and no error occurred.

Could you try followings?

1. use the binary directly: ./haproxy -f config
2. use a different dir and start `dir /opt/nuster/cache2` 
3. use a clean OS, git clone, make, and start

**Comment by jiangwenyuan** [comment]
@netrixken Reproduced it when dealing with another issue, should be fixed now in H2.1

https://github.com/jiangwenyuan/nuster/commit/99c60fbdaf880ce0bd34cf6cbb7ed001e46ea5ef

Could you please try again?

Thanks!

**Comment by netrixken** [comment]
has been running for 20 minutes by now, with no error. i think it's fixed, will report it back if this reproduced again.

i'm sorry, i can't give you anything, but thank you very much.

**Comment by jiangwenyuan** [comment]
Thank you so much! I'm closing it for now, feel free to reopen if it happens again
